development:
  adapter: 'sqlite3'
  name: 'development.db'

test:
  adapter: 'sqlite3'
  name: 'test.db'

production:
    adapter: db.scheme == 'postgres' ? 'postgresql' : db.scheme,
    database: URI.parse(ENV['DATABASE_URL'] || 'postgres://localhost/mydb'
    host: db.host,
    username: db.user,
    password: db.password,
    database: db.path[1..-1],
    encoding: 'utf8'
